// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    /// <summary>
    /// Constants
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class APIConfigConstants : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Group-related constants</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_GROUPS? GROUPS { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_GROUPS GROUPS { get; set; }
#endif
        /// <summary>Instance-related constants</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_INSTANCE? INSTANCE { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_INSTANCE INSTANCE { get; set; }
#endif
        /// <summary>Language-related constants</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_LANGUAGE? LANGUAGE { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_LANGUAGE LANGUAGE { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants"/> and sets the default values.
        /// </summary>
        public APIConfigConstants()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "GROUPS", n => { GROUPS = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_GROUPS>(global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_GROUPS.CreateFromDiscriminatorValue); } },
                { "INSTANCE", n => { INSTANCE = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_INSTANCE>(global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_INSTANCE.CreateFromDiscriminatorValue); } },
                { "LANGUAGE", n => { LANGUAGE = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_LANGUAGE>(global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_LANGUAGE.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_GROUPS>("GROUPS", GROUPS);
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_INSTANCE>("INSTANCE", INSTANCE);
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.APIConfigConstants_LANGUAGE>("LANGUAGE", LANGUAGE);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
