// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    /// <summary>Used to identify which API deployment cluster is currently responding.`blue` and `green` are used by Production.`grape`and `cherry` are used during Development.[Blue Green Deployment by Martin Fowler](https://martinfowler.com/bliki/BlueGreenDeployment.html)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeploymentGroup
    {
        [EnumMember(Value = "blue")]
        #pragma warning disable CS1591
        Blue,
        #pragma warning restore CS1591
        [EnumMember(Value = "green")]
        #pragma warning disable CS1591
        Green,
        #pragma warning restore CS1591
        [EnumMember(Value = "grape")]
        #pragma warning disable CS1591
        Grape,
        #pragma warning restore CS1591
        [EnumMember(Value = "cherry")]
        #pragma warning disable CS1591
        Cherry,
        #pragma warning restore CS1591
    }
}
