// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    /// <summary>&quot;none&quot; User is a normal user&quot;trusted&quot; Unknown&quot;internal&quot; Is a VRChat Developer&quot;moderator&quot; Is a VRChat ModeratorStaff can hide their developerType at will.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeveloperType
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "trusted")]
        #pragma warning disable CS1591
        Trusted,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal")]
        #pragma warning disable CS1591
        Internal,
        #pragma warning restore CS1591
        [EnumMember(Value = "moderator")]
        #pragma warning disable CS1591
        Moderator,
        #pragma warning restore CS1591
    }
}
