// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "waiting")]
        #pragma warning disable CS1591
        Waiting,
        #pragma warning restore CS1591
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
    }
}
