// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileData_category
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "multipart")]
        #pragma warning disable CS1591
        Multipart,
        #pragma warning restore CS1591
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "simple")]
        #pragma warning disable CS1591
        Simple,
        #pragma warning restore CS1591
    }
}
