// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FileVersion : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Usually only present if `true`</summary>
        public bool? Deleted { get; set; }
        /// <summary>The delta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.FileData? Delta { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.FileData Delta { get; set; }
#endif
        /// <summary>The file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.FileData? File { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.FileData File { get; set; }
#endif
        /// <summary>The signature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VRCZ.VRChatApi.Generated.Models.FileData? Signature { get; set; }
#nullable restore
#else
        public global::VRCZ.VRChatApi.Generated.Models.FileData Signature { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::VRCZ.VRChatApi.Generated.Models.FileStatus? Status { get; set; }
        /// <summary>Incremental version counter, can only be increased.</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Models.FileVersion"/> and sets the default values.
        /// </summary>
        public FileVersion()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::VRCZ.VRChatApi.Generated.Models.FileStatus.Waiting;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VRCZ.VRChatApi.Generated.Models.FileVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VRCZ.VRChatApi.Generated.Models.FileVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::VRCZ.VRChatApi.Generated.Models.FileVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "delta", n => { Delta = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>(global::VRCZ.VRChatApi.Generated.Models.FileData.CreateFromDiscriminatorValue); } },
                { "file", n => { File = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>(global::VRCZ.VRChatApi.Generated.Models.FileData.CreateFromDiscriminatorValue); } },
                { "signature", n => { Signature = n.GetObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>(global::VRCZ.VRChatApi.Generated.Models.FileData.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::VRCZ.VRChatApi.Generated.Models.FileStatus>(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>("delta", Delta);
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>("file", File);
            writer.WriteObjectValue<global::VRCZ.VRChatApi.Generated.Models.FileData>("signature", Signature);
            writer.WriteEnumValue<global::VRCZ.VRChatApi.Generated.Models.FileStatus>("status", Status);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
