// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    /// <summary>Group access type when the instance type is &quot;group&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupAccessType
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "plus")]
        #pragma warning disable CS1591
        Plus,
        #pragma warning restore CS1591
        [EnumMember(Value = "members")]
        #pragma warning disable CS1591
        Members,
        #pragma warning restore CS1591
    }
}
