// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GroupJoinState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite")]
        #pragma warning disable CS1591
        Invite,
        #pragma warning restore CS1591
        [EnumMember(Value = "request")]
        #pragma warning disable CS1591
        Request,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
    }
}
