// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GroupUserVisibility
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "visible")]
        #pragma warning disable CS1591
        Visible,
        #pragma warning restore CS1591
        [EnumMember(Value = "hidden")]
        #pragma warning disable CS1591
        Hidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "friends")]
        #pragma warning disable CS1591
        Friends,
        #pragma warning restore CS1591
    }
}
