// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LicenseType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "avatar")]
        #pragma warning disable CS1591
        Avatar,
        #pragma warning restore CS1591
        [EnumMember(Value = "licenseGroup")]
        #pragma warning disable CS1591
        LicenseGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission")]
        #pragma warning disable CS1591
        Permission,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
    }
}
