// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    /// <summary>Avatar Performance ratings.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PerformanceRatings
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Excellent")]
        #pragma warning disable CS1591
        Excellent,
        #pragma warning restore CS1591
        [EnumMember(Value = "Good")]
        #pragma warning disable CS1591
        Good,
        #pragma warning restore CS1591
        [EnumMember(Value = "Medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "Poor")]
        #pragma warning disable CS1591
        Poor,
        #pragma warning restore CS1591
        [EnumMember(Value = "VeryPoor")]
        #pragma warning disable CS1591
        VeryPoor,
        #pragma warning restore CS1591
    }
}
