// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PlayerModerationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mute")]
        #pragma warning disable CS1591
        Mute,
        #pragma warning restore CS1591
        [EnumMember(Value = "unmute")]
        #pragma warning disable CS1591
        Unmute,
        #pragma warning restore CS1591
        [EnumMember(Value = "block")]
        #pragma warning disable CS1591
        Block,
        #pragma warning restore CS1591
        [EnumMember(Value = "unblock")]
        #pragma warning disable CS1591
        Unblock,
        #pragma warning restore CS1591
        [EnumMember(Value = "interactOn")]
        #pragma warning disable CS1591
        InteractOn,
        #pragma warning restore CS1591
        [EnumMember(Value = "interactOff")]
        #pragma warning disable CS1591
        InteractOff,
        #pragma warning restore CS1591
    }
}
