// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Finish;
using VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Start;
using VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Status;
namespace VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \file\{fileId}\{versionId}\{fileType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFileTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The finish property</summary>
        public global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Finish.FinishRequestBuilder Finish
        {
            get => new global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Finish.FinishRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Start.StartRequestBuilder Start
        {
            get => new global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Status.StatusRequestBuilder Status
        {
            get => new global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.WithFileTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/file/{fileId}/{versionId}/{fileType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.FileNamespace.Item.Item.Item.WithFileTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/file/{fileId}/{versionId}/{fileType}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
