// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.Avatars.Impostor.Queue;
namespace VRCZ.VRChatApi.Generated.Avatars.Impostor
{
    /// <summary>
    /// Builds and executes requests for operations under \avatars\impostor
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImpostorRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The queue property</summary>
        public global::VRCZ.VRChatApi.Generated.Avatars.Impostor.Queue.QueueRequestBuilder Queue
        {
            get => new global::VRCZ.VRChatApi.Generated.Avatars.Impostor.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Avatars.Impostor.ImpostorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImpostorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/avatars/impostor", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Avatars.Impostor.ImpostorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImpostorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/avatars/impostor", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
