// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.Users.Item.Badges.Item;
namespace VRCZ.VRChatApi.Generated.Users.Item.Badges
{
    /// <summary>
    /// Builds and executes requests for operations under \users\{user-id}\badges
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BadgesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VRCZ.VRChatApi.Generated.users.item.badges.item collection</summary>
        /// <param name="position">Must be a valid badge ID.</param>
        /// <returns>A <see cref="global::VRCZ.VRChatApi.Generated.Users.Item.Badges.Item.WithBadgeItemRequestBuilder"/></returns>
        public global::VRCZ.VRChatApi.Generated.Users.Item.Badges.Item.WithBadgeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("badgeId", position);
                return new global::VRCZ.VRChatApi.Generated.Users.Item.Badges.Item.WithBadgeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Users.Item.Badges.BadgesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BadgesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}/badges", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Users.Item.Badges.BadgesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BadgesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}/badges", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
