// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.Favorite.Group;
using VRCZ.VRChatApi.Generated.Favorite.Groups;
namespace VRCZ.VRChatApi.Generated.Favorite
{
    /// <summary>
    /// Builds and executes requests for operations under \favorite
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FavoriteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The group property</summary>
        public global::VRCZ.VRChatApi.Generated.Favorite.Group.GroupRequestBuilder Group
        {
            get => new global::VRCZ.VRChatApi.Generated.Favorite.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::VRCZ.VRChatApi.Generated.Favorite.Groups.GroupsRequestBuilder Groups
        {
            get => new global::VRCZ.VRChatApi.Generated.Favorite.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Favorite.FavoriteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FavoriteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/favorite", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Favorite.FavoriteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FavoriteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/favorite", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
