// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.Invite.Myself.To.WithWorldIdWithInstanceId;
namespace VRCZ.VRChatApi.Generated.Invite.Myself.To
{
    /// <summary>
    /// Builds and executes requests for operations under \invite\myself\to
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Invite.Myself.To.ToRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invite/myself/to", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Invite.Myself.To.ToRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invite/myself/to", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \invite\myself\to\{worldId}:{instanceId}
        /// </summary>
        /// <returns>A <see cref="global::VRCZ.VRChatApi.Generated.Invite.Myself.To.WithWorldIdWithInstanceId.WithWorldIdWithInstanceIdRequestBuilder"/></returns>
        /// <param name="instanceId">Must be a valid instance ID.</param>
        /// <param name="worldId">Must be a valid world ID.</param>
        public global::VRCZ.VRChatApi.Generated.Invite.Myself.To.WithWorldIdWithInstanceId.WithWorldIdWithInstanceIdRequestBuilder WithWorldIdWithInstanceId(string instanceId, string worldId)
        {
            if(string.IsNullOrEmpty(instanceId)) throw new ArgumentNullException(nameof(instanceId));
            if(string.IsNullOrEmpty(worldId)) throw new ArgumentNullException(nameof(worldId));
            return new global::VRCZ.VRChatApi.Generated.Invite.Myself.To.WithWorldIdWithInstanceId.WithWorldIdWithInstanceIdRequestBuilder(PathParameters, RequestAdapter, instanceId, worldId);
        }
    }
}
#pragma warning restore CS0618
