// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VRCZ.VRChatApi.Generated.Js.AppJs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetVariantQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal")]
        #pragma warning disable CS1591
        Internal,
        #pragma warning restore CS1591
    }
}
