// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.Item;
namespace VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{groupId}\members\{userId}\roles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RolesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VRCZ.VRChatApi.Generated.groups.item.members.item.roles.item collection</summary>
        /// <param name="position">Must be a valid group role ID.</param>
        /// <returns>A <see cref="global::VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.Item.WithGroupRoleItemRequestBuilder"/></returns>
        public global::VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.Item.WithGroupRoleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("groupRoleId", position);
                return new global::VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.Item.WithGroupRoleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.RolesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RolesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupId}/members/{userId}/roles", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VRCZ.VRChatApi.Generated.Groups.Item.Members.Item.Roles.RolesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RolesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupId}/members/{userId}/roles", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
